export type DuaCategory = "morning" | "evening" | "afterSalah" | "special";

export interface Dua {
  id: string;
  category: DuaCategory;
  title: string;
  arabic: string;
  transliteration: string;
  translation: string;
  source: string;
  count?: number;
}

export const DUAS: Dua[] = [
  // ───── MORNING AZKAR ─────
  {
    id: "morning_1",
    category: "morning",
    title: "Morning Tasbih",
    arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ، لَا إِلٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ",
    transliteration: "Asbahna wa asbahal mulku lillah, wal hamdu lillah, la ilaha illAllahu wahdahu la sharika lah",
    translation: "We have reached the morning and at this very time unto Allah belongs all sovereignty, and all praise is for Allah. None has the right to be worshipped except Allah, alone.",
    source: "Abu Dawood",
    count: 1,
  },
  {
    id: "morning_2",
    category: "morning",
    title: "Protection Dua",
    arabic: "اَللّٰهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ",
    transliteration: "Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namootu wa ilaykan nushoor",
    translation: "O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is the resurrection.",
    source: "Tirmidhi",
    count: 1,
  },
  {
    id: "morning_3",
    category: "morning",
    title: "Ayat al-Kursi",
    arabic: "اَللّٰهُ لَا إِلٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ",
    transliteration: "Allahu la ilaha illa Huwal-Hayyul-Qayyum. La ta'khudhuhu sinatun wala nawm...",
    translation: "Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep.",
    source: "Quran 2:255",
    count: 1,
  },
  {
    id: "morning_4",
    category: "morning",
    title: "Sayyidul Istighfar",
    arabic: "اَللّٰهُمَّ أَنْتَ رَبِّي لَا إِلٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ",
    transliteration: "Allahumma anta rabbi la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't...",
    translation: "O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can.",
    source: "Sahih Bukhari",
    count: 1,
  },
  {
    id: "morning_5",
    category: "morning",
    title: "Durood in the Morning",
    arabic: "اَللّٰهُمَّ صَلِّ عَلٰى سَيِّدِنَا مُحَمَّدٍ وَعَلٰى آلِ مُحَمَّدٍ",
    transliteration: "Allahumma salli 'ala Sayyidina Muhammadin wa 'ala aali Muhammad",
    translation: "O Allah, send blessings upon our Master Muhammad and upon the family of Muhammad.",
    source: "Agreed Upon",
    count: 10,
  },
  {
    id: "morning_6",
    category: "morning",
    title: "Surah Al-Ikhlas + Al-Falaq + An-Nas",
    arabic: "قُلْ هُوَ اللّٰهُ أَحَدٌ ۝ اللّٰهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ",
    transliteration: "Qul Huwallahu Ahad, Allahus Samad, Lam yalid wa lam yulad, wa lam yakun lahu kufuwan ahad",
    translation: "Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. Nor is there to Him any equivalent.",
    source: "Quran 112 — read 3× morning & evening",
    count: 3,
  },
  // ───── EVENING AZKAR ─────
  {
    id: "evening_1",
    category: "evening",
    title: "Evening Opening",
    arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ",
    transliteration: "Amsayna wa amsal mulku lillah, wal hamdu lillah, la ilaha illAllahu wahdahu la sharika lah",
    translation: "We have reached the evening and at this very time unto Allah belongs all sovereignty, and all praise is for Allah.",
    source: "Abu Dawood",
    count: 1,
  },
  {
    id: "evening_2",
    category: "evening",
    title: "Evening Protection",
    arabic: "اَللّٰهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ",
    transliteration: "Allahumma inni as'alukal 'afiyata fid-dunya wal-akhirah",
    translation: "O Allah, I ask You for well-being in this world and in the Hereafter.",
    source: "Ibn Majah",
    count: 1,
  },
  {
    id: "evening_3",
    category: "evening",
    title: "Ayat al-Kursi (Evening)",
    arabic: "اَللّٰهُ لَا إِلٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ",
    transliteration: "Allahu la ilaha illa Huwal-Hayyul-Qayyum...",
    translation: "Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence.",
    source: "Quran 2:255 — read 1× every evening",
    count: 1,
  },
  {
    id: "evening_4",
    category: "evening",
    title: "Evening Istigfar",
    arabic: "أَسْتَغْفِرُ اللّٰهَ الْعَظِيمَ الَّذِي لَا إِلٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
    transliteration: "Astaghfirullah al-'Azeemal-ladhi la ilaha illa Huwal-Hayyul-Qayyumu wa atubu ilayh",
    translation: "I seek forgiveness from Allah the Almighty, besides Whom none has the right to be worshipped, the Ever-Living, the Sustainer, and I repent to Him.",
    source: "Abu Dawood, Tirmidhi",
    count: 3,
  },
  {
    id: "evening_5",
    category: "evening",
    title: "Durood in the Evening",
    arabic: "اَللّٰهُمَّ صَلِّ عَلٰى سَيِّدِنَا مُحَمَّدٍ وَعَلٰى آلِهِ وَصَحْبِهِ وَسَلِّمْ",
    transliteration: "Allahumma salli 'ala Sayyidina Muhammadin wa 'ala alihi wa sahbihi wa sallim",
    translation: "O Allah, send blessings upon our Master Muhammad and upon his family and companions.",
    source: "Agreed Upon",
    count: 10,
  },
  // ───── AFTER SALAH ─────
  {
    id: "after_1",
    category: "afterSalah",
    title: "Tasbeeh-e-Fatima",
    arabic: "سُبْحَانَ اللّٰهِ × ٣٣ ، اَلْحَمْدُ لِلّٰهِ × ٣٣ ، اَللّٰهُ أَكْبَرُ × ٣٤",
    transliteration: "SubhanAllah ×33, Alhamdulillah ×33, Allahu Akbar ×34",
    translation: "Glory be to Allah (33×), All praise is for Allah (33×), Allah is the Greatest (34×)",
    source: "Sahih Bukhari & Muslim — Sunnah after every Salah",
    count: 100,
  },
  {
    id: "after_2",
    category: "afterSalah",
    title: "After Salah Dua",
    arabic: "اَللّٰهُمَّ أَعِنِّي عَلٰى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
    transliteration: "Allahumma a'inni 'ala dhikrika wa shukrika wa husni 'ibadatik",
    translation: "O Allah, help me in remembering You, in being grateful to You, and in worshipping You in the best manner.",
    source: "Abu Dawood — recommended after every Salah",
    count: 1,
  },
  {
    id: "after_3",
    category: "afterSalah",
    title: "Dua for Forgiveness",
    arabic: "اَللّٰهُمَّ اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ وَالْمُؤْمِنَاتِ",
    transliteration: "Allahummaghfir li wa li-walidayya wa lil-mu'mineena wal-mu'minat",
    translation: "O Allah, forgive me, my parents, and all believing men and women.",
    source: "Quran 71:28",
    count: 1,
  },
  {
    id: "after_4",
    category: "afterSalah",
    title: "La ilaha illAllah",
    arabic: "لَا إِلٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلٰى كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration: "La ilaha illAllahu wahdahu la sharika lah, lahul mulku wa lahul hamdu wa Huwa 'ala kulli shay'in Qadeer",
    translation: "None has the right to be worshipped but Allah, alone, without partner. To Him belongs all sovereignty and praise and He is over all things omnipotent.",
    source: "Sahih Muslim — 10× after Fajr & Maghrib removes 10 sins",
    count: 10,
  },
  {
    id: "after_5",
    category: "afterSalah",
    title: "Darood-e-Ibrahimi",
    arabic: "اَللّٰهُمَّ صَلِّ عَلٰى مُحَمَّدٍ وَعَلٰى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلٰى إِبْرَاهِيمَ وَعَلٰى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ",
    transliteration: "Allahumma salli 'ala Muhammadin wa 'ala aali Muhammadin kama sallayta 'ala Ibrahima wa 'ala aali Ibrahim, innaka Hamidum Majid",
    translation: "O Allah, bless Muhammad and the family of Muhammad as You have blessed Ibrahim and the family of Ibrahim. Indeed, You are Praiseworthy and Glorious.",
    source: "Sahih Bukhari — part of Tashahhud",
    count: 1,
  },
  // ───── SPECIAL / WAZAIF ─────
  {
    id: "special_1",
    category: "special",
    title: "Darood-e-Taj (Barelvi)",
    arabic: "اَللّٰهُمَّ صَلِّ عَلٰى سَيِّدِنَا وَمَوْلَانَا مُحَمَّدٍ ۨصَاحِبِ التَّاجِ وَالْمِعْرَاجِ وَالْبُرَاقِ وَالْعَلَمِ",
    transliteration: "Allahumma salli 'ala Sayyidina wa Mawlana Muhammadin, Sahibit-Taji wal-Mi'raji wal-Buraqi wal-'Alam...",
    translation: "O Allah, send blessings upon our Master and Leader Muhammad, the possessor of the Crown, the Mi'raj, the Buraq and the Standard...",
    source: "Barelvi-Sufi Tradition — read 11× daily",
    count: 11,
  },
  {
    id: "special_2",
    category: "special",
    title: "Dua-e-Qunoot",
    arabic: "اَللّٰهُمَّ إِنَّا نَسْتَعِينُكَ وَنَسْتَغْفِرُكَ وَنُؤْمِنُ بِكَ وَنَتَوَكَّلُ عَلَيْكَ وَنُثْنِي عَلَيْكَ الْخَيْرَ",
    transliteration: "Allahumma inna nasta'eenuka wa nastaghfiruka wa nu'minu bika wa natawakkalu 'alayk...",
    translation: "O Allah, we seek Your help and seek Your forgiveness, and we believe in You and rely on You, and we praise You for all good.",
    source: "Witr Prayer — Abu Dawood",
    count: 1,
  },
  {
    id: "special_3",
    category: "special",
    title: "Dua for Protection (Ruqyah)",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللّٰهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transliteration: "A'udhu bi kalimati Allahit-tammati min sharri ma khalaq",
    translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    source: "Sahih Muslim — read 3× every evening",
    count: 3,
  },
  {
    id: "special_4",
    category: "special",
    title: "Ya Hayyu Ya Qayyum",
    arabic: "يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ وَلَا تَكِلْنِي إِلٰى نَفْسِي طَرْفَةَ عَيْنٍ",
    transliteration: "Ya Hayyu Ya Qayyumu bi-rahmatika astaghith, aslih li sha'ni kullahu wa la takilni ila nafsi tarfata 'ayn",
    translation: "O Ever Living, O Self-Sustaining and Supporter of all, by Your mercy I seek assistance. Rectify for me all of my affairs and do not leave me to myself, even for the blink of an eye.",
    source: "Hakim — recommended for distress",
    count: 1,
  },
  {
    id: "special_5",
    category: "special",
    title: "Dua for Rizq (Provision)",
    arabic: "اَللّٰهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ، وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
    transliteration: "Allahummak-fini bi-halalika 'an haramik, wa aghnini bi-fadlika 'amman siwak",
    translation: "O Allah, suffice me with what You have allowed instead of what You have forbidden, and make me independent of all others besides You.",
    source: "Tirmidhi",
    count: 1,
  },
  {
    id: "special_6",
    category: "special",
    title: "Dua for Shifa (Healing)",
    arabic: "اَللّٰهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ، وَاشْفِ أَنْتَ الشَّافِي، لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا",
    transliteration: "Allahumma Rabban-nasi adhhibil-ba's, washfi Antash-Shafi, la shifa'a illa shifa'uk, shifa'an la yughadiru saqama",
    translation: "O Allah, Lord of mankind, remove the harm and cure, for You are the Curer. There is no cure except Your cure, a cure that leaves no illness.",
    source: "Sahih Bukhari — Dua of Prophet ﷺ for the sick",
    count: 3,
  },
  {
    id: "special_7",
    category: "special",
    title: "Surah Al-Fatiha (Wazifa)",
    arabic: "بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيمِ ۝ اَلْحَمْدُ لِلّٰهِ رَبِّ الْعَالَمِينَ ۝ الرَّحْمٰنِ الرَّحِيمِ ۝ مَالِكِ يَوْمِ الدِّينِ",
    transliteration: "Bismillahir-Rahmanir-Raheem. Alhamdu lillahi Rabbil-'aalameen. Ar-Rahmanir-Raheem. Maliki yawmid-deen...",
    translation: "In the name of Allah, the Most Gracious, the Most Merciful. All praise is for Allah, Lord of all worlds. The Most Gracious, the Most Merciful. Master of the Day of Judgment...",
    source: "Quran 1:1-7 — the greatest surah, read with intention for Fatiha Khwani",
    count: 7,
  },
  {
    id: "special_8",
    category: "special",
    title: "Dua for Parents",
    arabic: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    transliteration: "Rabbir-hamhuma kama rabbayani sagheera",
    translation: "My Lord, have mercy upon them as they brought me up when I was small.",
    source: "Quran 17:24 — read for living and deceased parents",
    count: 3,
  },
];

export const DUA_CATEGORIES: { key: DuaCategory; icon: string }[] = [
  { key: "morning",    icon: "☀️" },
  { key: "evening",   icon: "🌙" },
  { key: "afterSalah", icon: "🕌" },
  { key: "special",   icon: "⭐" },
];
